const data = [
  {
    city: "Skopje",
    lat: "41.9833",
    lng: "21.4333",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Skopje",
    capital: "primary",
    population: "640000",
    population_proper: "640000",
  },
  {
    city: "Tetovo",
    lat: "42.0103",
    lng: "20.9714",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Tetovo",
    capital: "admin",
    population: "142030",
    population_proper: "142030",
  },
  {
    city: "Bitola",
    lat: "41.0319",
    lng: "21.3347",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Bitola",
    capital: "admin",
    population: "84002",
    population_proper: "84002",
  },
  {
    city: "Kumanovo",
    lat: "42.1403",
    lng: "21.7136",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Kumanovo",
    capital: "admin",
    population: "70842",
    population_proper: "70842",
  },
  {
    city: "Prilep",
    lat: "41.3464",
    lng: "21.5542",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Prilep",
    capital: "admin",
    population: "66817",
    population_proper: "66817",
  },
  {
    city: "Ohrid",
    lat: "41.1169",
    lng: "20.8019",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Ohrid",
    capital: "admin",
    population: "55749",
    population_proper: "55749",
  },
  {
    city: "Strumica",
    lat: "41.4375",
    lng: "22.6431",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Strumica",
    capital: "admin",
    population: "45087",
    population_proper: "45087",
  },
  {
    city: "Veles",
    lat: "41.7153",
    lng: "21.7753",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Veles",
    capital: "admin",
    population: "45037",
    population_proper: "45037",
  },
  {
    city: "Probistip",
    lat: "41.7358",
    lng: "22.1914",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Probistip",
    capital: "admin",
    population: "43652",
    population_proper: "43652",
  },
  {
    city: "Kavadarci",
    lat: "41.4328",
    lng: "22.0117",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Kavadarci",
    capital: "admin",
    population: "38741",
    population_proper: "38741",
  },
  {
    city: "Gostivar",
    lat: "41.8000",
    lng: "20.9167",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Gostivar",
    capital: "admin",
    population: "35847",
    population_proper: "35847",
  },
  {
    city: "Kochani",
    lat: "41.9167",
    lng: "22.4125",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Kochani",
    capital: "admin",
    population: "28330",
    population_proper: "28330",
  },
  {
    city: "Kichevo",
    lat: "41.5142",
    lng: "20.9631",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Kichevo",
    capital: "admin",
    population: "27067",
    population_proper: "27067",
  },
  {
    city: "Struga",
    lat: "41.1775",
    lng: "20.6789",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Struga",
    capital: "admin",
    population: "16559",
    population_proper: "16559",
  },
  {
    city: "Radovis",
    lat: "41.6381",
    lng: "22.4644",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Radovis",
    capital: "admin",
    population: "16223",
    population_proper: "16223",
  },
  {
    city: "Gevgelija",
    lat: "41.1392",
    lng: "22.5025",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Gevgelija",
    capital: "admin",
    population: "15685",
    population_proper: "15685",
  },
  {
    city: "Debar",
    lat: "41.5250",
    lng: "20.5272",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Debar",
    capital: "admin",
    population: "14561",
    population_proper: "14561",
  },
  {
    city: "Kriva Palanka",
    lat: "42.2017",
    lng: "22.3317",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Kriva Palanka",
    capital: "admin",
    population: "14558",
    population_proper: "14558",
  },
  {
    city: "Sveti Nikole",
    lat: "41.8650",
    lng: "21.9425",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Sveti Nikole",
    capital: "admin",
    population: "13746",
    population_proper: "13746",
  },
  {
    city: "Negotino",
    lat: "41.4839",
    lng: "22.0892",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Negotino",
    capital: "admin",
    population: "13284",
    population_proper: "13284",
  },
  {
    city: "Delcevo",
    lat: "41.9661",
    lng: "22.7747",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Delcevo",
    capital: "admin",
    population: "11500",
    population_proper: "11500",
  },
  {
    city: "Vinica",
    lat: "41.8828",
    lng: "22.5092",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Vinica",
    capital: "admin",
    population: "10863",
    population_proper: "10863",
  },
  {
    city: "Berovo",
    lat: "41.7078",
    lng: "22.8564",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Berovo",
    capital: "admin",
    population: "7002",
    population_proper: "7002",
  },
  {
    city: "Kratovo",
    lat: "42.0783",
    lng: "22.1750",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Kratovo",
    capital: "admin",
    population: "6924",
    population_proper: "6924",
  },
  {
    city: "Bogdanci",
    lat: "41.2031",
    lng: "22.5728",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Bogdanci",
    capital: "admin",
    population: "6031",
    population_proper: "6031",
  },
  {
    city: "Krusevo",
    lat: "41.3700",
    lng: "21.2483",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Krusevo",
    capital: "admin",
    population: "5507",
    population_proper: "5507",
  },
  {
    city: "Valandovo",
    lat: "41.3169",
    lng: "22.5611",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Valandovo",
    capital: "admin",
    population: "4442",
    population_proper: "4442",
  },
  {
    city: "Makedonski Brod",
    lat: "41.5133",
    lng: "21.2153",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Makedonski Brod",
    capital: "admin",
    population: "3740",
    population_proper: "3740",
  },
  {
    city: "Pehcevo",
    lat: "41.7592",
    lng: "22.8906",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Pehcevo",
    capital: "admin",
    population: "3237",
    population_proper: "3237",
  },
  {
    city: "Probistip",
    lat: "41.9936",
    lng: "22.1767",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Probistip",
    capital: "admin",
    population: "3110",
    population_proper: "3110",
  },
  {
    city: "Demir Hisar",
    lat: "41.2208",
    lng: "21.2031",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Demir Hisar",
    capital: "admin",
    population: "2593",
    population_proper: "2593",
  },
  {
    city: "Demir Kapija",
    lat: "41.4114",
    lng: "22.2422",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Demir Kapija",
    capital: "admin",
    population: "2547",
    population_proper: "2547",
  },
  {
    city: "Vevcani",
    lat: "41.2406",
    lng: "20.5933",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Vev\u010dani",
    capital: "admin",
    population: "",
    population_proper: "",
  },
  {
    city: "Makedonska Kamenica",
    lat: "42.0208",
    lng: "22.5876",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Makedonska Kamenica",
    capital: "admin",
    population: "",
    population_proper: "",
  },
  {
    city: "Resen",
    lat: "41.0893",
    lng: "21.0109",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Resen",
    capital: "admin",
    population: "",
    population_proper: "",
  },
  {
    city: "Star Dojran",
    lat: "41.1792",
    lng: "22.7247",
    country: "Macedonia",
    iso2: "MK",
    admin_name: "Dojran",
    capital: "admin",
    population: "",
    population_proper: "",
  },
];

export default data;
